[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "link-arg=--allow-undefined",
  "-C",
  "target-feature=-bulk-memory",
]

[target.wasm32v1-none]
rustflags = ["-C", "link-arg=--allow-undefined"]
